# BIOS470/570 Lecture 2

## Last time we covered:
* ### Using github to manage code
* ### Using the conda package manager to create environments and install packages
* ### Basic variable types in python (int, float, str, bool)
* ### = vs ==
* ### Lists and slicing

## Today we will cover:
* ### other builtin python types for storing collections of objects
* ### mutable vs immutable
* ### copy vs view
* ### basic conditional and loops
* ### importing packages into the workspace

## Reminder: a list is a collection of objects. It is denoted by square brackets. List can contain mixtures of variable types including other lists. For example:

In [93]:
list1 = [78,"foo", [1, 3, 4], ["list", "of","strings"]]

In [94]:
print(list1[1])

foo


In [95]:
print(list1[2][1])

3


In [96]:
print(list1[3][2])

strings


## A tuple is very similar to a list, denoted by parenthesis:

In [97]:
tup1 = (1, 4.5, "string1", [1, 2.3, "string2"])
print(tup1)

(1, 4.5, 'string1', [1, 2.3, 'string2'])


## The key difference between tuples and lists is that lists are mutable while tuples are immutable:

In [98]:
#lists are mutable:
print(list1)
list1[0] = "New first element"
print(list1)

[78, 'foo', [1, 3, 4], ['list', 'of', 'strings']]
['New first element', 'foo', [1, 3, 4], ['list', 'of', 'strings']]


In [99]:
# tuples are immutable:
print(tup1)
print(tup1[0]) #Note defition uses parenthesis but accessing elements usings brackets. 
tup1[0] = "New first tup element"

(1, 4.5, 'string1', [1, 2.3, 'string2'])
1


TypeError: 'tuple' object does not support item assignment

### So how can I make a new tuple with a different first element:

In [100]:
tup2 = ("New first tup element", tup1[1:]) #this almost works 
print(tup2)

('New first tup element', (4.5, 'string1', [1, 2.3, 'string2']))


In [101]:
tup3 = ("New first tup element",)+tup1[1:] #this gives the desired result
print(tup3)

('New first tup element', 4.5, 'string1', [1, 2.3, 'string2'])


## A set is an unordered collection of objects. Sets are mutable so you can add to them

In [102]:
set1 = {"a",1,4.5}
print(set1)
set1.add(92)
print(set1)
set1.remove(1)
print(set1)

{'a', 1, 4.5}
{'a', 1, 4.5, 92}
{'a', 4.5, 92}


In [103]:
## You can check the contents of any of these types:
print('a' in set1)
print('a' in list1)

True
False


## Dictionaries are collections of objects each of which can be referenced by a key.

In [104]:
dict1 = {"a":12,"b":23,"c":98}
print(dict1["b"])
print(dict1["c"])

23
98


### Dictionaries are mutable so you can add and delete keys and values:

In [105]:
dict1["d"] = 45
print(dict1)
del dict1["a"]
print(dict1)

{'a': 12, 'b': 23, 'c': 98, 'd': 45}
{'b': 23, 'c': 98, 'd': 45}


## When you set two arrays equal, you are not creating a new array but a new object with a view of the same data. 
### This matters because if you change one, the other will also change:

In [106]:
a = [1, 2, 3, 4, 5, 6]
b = a
print("a is ",a," and b is ",b)

a is  [1, 2, 3, 4, 5, 6]  and b is  [1, 2, 3, 4, 5, 6]


In [107]:
b[3] = 185
print("a is ",a," and b is ",b)

a is  [1, 2, 3, 185, 5, 6]  and b is  [1, 2, 3, 185, 5, 6]


## Note that if you use b = ... b will be completely reassigned and the link to a will be broken


In [108]:
b = [1, 2, 3]
print("a is ",a," and b is ",b)

a is  [1, 2, 3, 185, 5, 6]  and b is  [1, 2, 3]


## If you want to create a completely new object, use the copy function

In [109]:
b = a.copy()
print("a is ",a," and b is ",b)

a is  [1, 2, 3, 185, 5, 6]  and b is  [1, 2, 3, 185, 5, 6]


In [110]:
b[3] = 4
print("a is ",a," and b is ",b)

a is  [1, 2, 3, 185, 5, 6]  and b is  [1, 2, 3, 4, 5, 6]


## You can use the "is" keyword to test if two objects contain the same data. 

In [111]:
b = a.copy()
c = a
print(b==a)
print(c==a)

True
True


In [112]:
print(b is a)
print(c is a)

False
True


## Conditionals are ways to execute a piece of code only if something is true:

In [119]:
# note indentation and colon: 
num = -1
if num > 0:
    print("positive")
else:
    print("negative")
print("yes")

negative
yes


In [118]:
num = 0
if num > 0:
    print("positive")
elif num < 0:
    print("negative")
else:
    print("zero")

zero


## loops allow you to do something repeatedly. The range function is useful for iterating over:

In [123]:
list(range(1,5,2))

[1, 3]

In [125]:
for ii in range(10):
    print(ii)

0
1
2
3
4
5
6
7
8
9


## You can iterate over any of list, tuple, set...

In [126]:
for ii in list1:
    print(ii)

New first element
foo
[1, 3, 4]
['list', 'of', 'strings']


In [127]:
for ii in tup1:
    print(ii)

1
4.5
string1
[1, 2.3, 'string2']


In [129]:
for ii in dict1:
    print(ii,dict1[ii])

b 23
c 98
d 45


### what if we want to iterate through the values?

In [130]:
for vv in dict1.values():
    print(vv)

23
98
45


In [131]:
for kk,vv in dict1.items():
    print(kk,vv)

b 23
c 98
d 45


## Importing packages
#### Using the dir function, you will notice that there aren't very many functions built in to the base python. For example, basic mathematical functions such as logarithms or triginometric functions are missing. a common operation in processing transcriptomic data is to the log base 2 of the count numbers. Where can we find a function to do this? The numpy packages contains a wealth of functions for mathematical operations. 

In [ ]:
import numpy 

In [132]:
expr = [23, 81, 2, 19, 1000]
expr_log = numpy.log2(expr)
print(expr_log)

[4.52356196 6.33985    1.         4.24792751 9.96578428]


#### Note the type of expr_log. This is a very useful data type that we will discuss in detail next week. 

In [133]:
type(expr_log)

numpy.ndarray

### you can import a package and give it any name you want. This is the standard convention for numpy: 

In [134]:
import numpy as np
np.log2(expr)

array([4.52356196, 6.33985   , 1.        , 4.24792751, 9.96578428])

### If you only need one function, you can import it directly to your current workspace without a name:

In [135]:
from numpy import log2
log2(expr)

array([4.52356196, 6.33985   , 1.        , 4.24792751, 9.96578428])

#### 'from numpy import *' will import all functions but this is not recommended as it can lead to conflicts with other packages.

#### This will show all the objects and functions in the numpy space. There is a lot here than in python alone

In [136]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_bui